# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_BookAddWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookAddWindow(object):
    def setupUi(self, BookAddWindow):
        BookAddWindow.setObjectName("BookAddWindow")
        BookAddWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        BookAddWindow.resize(288, 279)
        self.Bpress = QtWidgets.QLineEdit(BookAddWindow)
        self.Bpress.setGeometry(QtCore.QRect(90, 109, 151, 20))
        self.Bpress.setObjectName("Bpress")
        self.label_2 = QtWidgets.QLabel(BookAddWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 108, 61, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.Bauthor = QtWidgets.QLineEdit(BookAddWindow)
        self.Bauthor.setGeometry(QtCore.QRect(90, 139, 151, 20))
        self.Bauthor.setObjectName("Bauthor")
        self.label_3 = QtWidgets.QLabel(BookAddWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 138, 41, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.submit = QtWidgets.QPushButton(BookAddWindow)
        self.submit.setGeometry(QtCore.QRect(120, 239, 56, 17))
        self.submit.setObjectName("submit")
        self.msg = QtWidgets.QLabel(BookAddWindow)
        self.msg.setGeometry(QtCore.QRect(0, 259, 291, 20))
        self.msg.setText("")
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setObjectName("msg")
        self.Bname = QtWidgets.QLineEdit(BookAddWindow)
        self.Bname.setGeometry(QtCore.QRect(90, 79, 151, 20))
        self.Bname.setObjectName("Bname")
        self.label_4 = QtWidgets.QLabel(BookAddWindow)
        self.label_4.setGeometry(QtCore.QRect(40, 78, 41, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(BookAddWindow)
        self.label_5.setGeometry(QtCore.QRect(40, 48, 41, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.B_ISBN = QtWidgets.QLineEdit(BookAddWindow)
        self.B_ISBN.setGeometry(QtCore.QRect(90, 49, 151, 20))
        self.B_ISBN.setObjectName("B_ISBN")
        self.label_6 = QtWidgets.QLabel(BookAddWindow)
        self.label_6.setGeometry(QtCore.QRect(40, 199, 41, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.Bposition = QtWidgets.QLineEdit(BookAddWindow)
        self.Bposition.setGeometry(QtCore.QRect(90, 200, 151, 20))
        self.Bposition.setObjectName("Bposition")
        self.label_7 = QtWidgets.QLabel(BookAddWindow)
        self.label_7.setGeometry(QtCore.QRect(20, 169, 61, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.Btype = QtWidgets.QLineEdit(BookAddWindow)
        self.Btype.setGeometry(QtCore.QRect(90, 170, 151, 20))
        self.Btype.setObjectName("Btype")
        self.label = QtWidgets.QLabel(BookAddWindow)
        self.label.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(BookAddWindow)
        self.submit.clicked.connect(BookAddWindow.do_submit)
        QtCore.QMetaObject.connectSlotsByName(BookAddWindow)
        BookAddWindow.setTabOrder(self.B_ISBN, self.Bname)
        BookAddWindow.setTabOrder(self.Bname, self.Bpress)
        BookAddWindow.setTabOrder(self.Bpress, self.Bauthor)
        BookAddWindow.setTabOrder(self.Bauthor, self.Btype)
        BookAddWindow.setTabOrder(self.Btype, self.Bposition)
        BookAddWindow.setTabOrder(self.Bposition, self.submit)

    def retranslateUi(self, BookAddWindow):
        _translate = QtCore.QCoreApplication.translate
        BookAddWindow.setWindowTitle(_translate("BookAddWindow", "图书登记"))
        self.label_2.setText(_translate("BookAddWindow", "出版社："))
        self.label_3.setText(_translate("BookAddWindow", "作者："))
        self.submit.setText(_translate("BookAddWindow", "提交"))
        self.label_4.setText(_translate("BookAddWindow", "书名："))
        self.label_5.setText(_translate("BookAddWindow", "ISBN："))
        self.label_6.setText(_translate("BookAddWindow", "位置："))
        self.label_7.setText(_translate("BookAddWindow", "所属类别："))
        self.label.setText(_translate("BookAddWindow", "图书登记"))

